fail_on_severity: 'high'
deny_licenses:  
  - 'LGPL-2.0'
  - 'APL-1.0'
  - 'AGPL-1.0'
  - 'AGPL-1.0-or-later'
  - 'APSL-1.0'
  - 'APSL-1.1'
  - 'APSL-1.2'
  - 'APSL-2.0'
  - 'BUSL-1.1'
  - 'CECILL-B'
  - 'CECILL-C'
  - 'CECILL-1.0'
  - 'CECILL-1.1'
  - 'CECILL-2.0'
  - 'CECILL-2.1'
  - 'CPOL-1.02'
  - 'CPAL-1.0'
  - 'CC-BY-1.0'
  - 'CC-BY-2.0'
  - 'CC-BY-2.5'
  - 'CC-BY-3.0-AT'
  - 'CC-BY-3.0-US'
  - 'CC-BY-3.0'
  - 'CC-BY-ND-1.0'
  - 'CC-BY-ND-2.0'
  - 'CC-BY-ND-2.5'
  - 'CC-BY-ND-3.0'
  - 'GPL-1.0-only'
  - 'GPL-1.0'
  - 'GPL-1.0-or-later'
  - 'GPL-1.0+'
  - 'GPL-2.0-only'
  - 'GPL-2.0'
  - 'GPL-2.0-or-later'
  - 'GPL-2.0+'
  - 'GPL-3.0-only'
  - 'GPL-3.0'
  - 'GPL-3.0-or-later'
  - 'GPL-3.0+'
  - 'LGPL-2.1-or-later'
  - 'LGPL-2.1+'
  - 'LGPL-3.0-only'
