fail_on_severity: 'high'
deny_licenses:
  - 'LGPL-2.0'
  - 'BSD-2-Clause'
  - 'SPDX Identifier'
  - '389-exception'
  - 'APL-1.0'
  - 'AGPL-1.0'
  - 'AGPL-1.0-only'
  - 'AGPL-1.0-or-later'
  - 'Aladdin'
  - 'APSL-1.0'
  - 'APSL-1.1'
  - 'APSL-1.2'
  - 'APSL-2.0'
  - 'GPL-2.0-with-autoconf-exception'
  - 'GPL-3.0-with-autoconf-exception'
  - 'GPL-2.0-with-bison-exception'
  - 'BitTorrent-1.0'
  - 'BitTorrent-1.1'
  - 'Bootloader-exception'
  - 'BUSL-1.1'
  - 'CECILL-B'
  - 'CECILL-C'
  - 'CECILL-1.0'
  - 'CECILL-1.1'
  - 'CECILL-2.0'
  - 'CECILL-2.1'
  - 'GPL-2.0-with-classpath-exception'
  - 'CLISP-exception-2.0'
  - 'CPOL-1.02'
  - 'CPAL-1.0'
  - 'CDLA-Sharing-1.0'
  - 'copyleft-next-0.3.0'
  - 'copyleft-next-0.3.1'
  - 'CC-BY-1.0'
  - 'CC-BY-2.0'
  - 'CC-BY-2.5'
  - 'CC-BY-3.0-AT'
  - 'CC-BY-3.0-US'
  - 'CC-BY-3.0'
  - 'CC-BY-ND-1.0'
  - 'CC-BY-ND-2.0'
  - 'CC-BY-ND-2.5'
  - 'CC-BY-ND-3.0'
  - 'GPL-1.0-only'
  - 'GPL-1.0'
  - 'GPL-1.0-or-later'
  - 'GPL-1.0+'
  - 'GPL-2.0-only'
  - 'GPL-2.0'
  - 'GPL-2.0-or-later'
  - 'GPL-2.0+'
  - 'GPL-2.0-with-autoconf-exception'
  - 'GPL-2.0-with-bison-exception'
  - 'GPL-2.0-with-font-exception'
  - 'GPL-2.0-with-GCC-exception'
  - 'GPL-3.0-only'
  - 'GPL-3.0'
  - 'GPL-3.0-or-later'
  - 'GPL-3.0+'
  - 'GPL-3.0-with-autoconf-exception'
  - 'GPL-3.0-with-GCC-exception'
  - 'LGPL-2.1-or-later'
  - 'LGPL-2.1+'
  - 'LGPL-3.0-only'
  - 'LGPL-3.0'
  - 'LGPL-3.0-only'
  - 'LGPL-3.0+'
  - 'MPL-1.0'
  - 'MPL-1.1'
  - 'OpenJDK-assembly-exception-1.0'
  - 'openvpn-openssl-exception'
  - 'SPL-1.0'
